"""Public access API used by routes and other modules."""

from app.modules.access.auth import (
    INVALID_CREDENTIALS_CODE,
    AuthSessionResult,
    authenticate_platform_user,
    authenticate_workshop_user,
    change_password,
)
from app.modules.access.authz import (
    BranchScope,
    can_access_branch,
    require_manage_orders_workshop,
    resolve_branch_scope,
    resolve_branch_scope_any,
    visible_branch_ids,
    visible_workshop_ids,
)
from app.modules.access.client_ip import resolve_client_ip
from app.modules.access.clients import (
    ClientResolution,
    find_or_create_client,
    normalize_uz_phone,
    pin_branch_on_order,
)
from app.modules.access.login_throttle import (
    LoginIpThrottle,
    SlidingWindowIpThrottle,
    login_throttle,
    telegram_code_throttle,
)
from app.modules.access.sessions import (
    ACCESS_TTL,
    MAX_SESSIONS_PER_PRINCIPAL,
    REFRESH_TTL,
    PlainSessionTokens,
    create_session,
    get_session_by_access_token,
    get_session_by_refresh_token,
    principal_from_session,
    prune_expired_sessions,
    refresh_session,
    revoke_for_principal,
    revoke_for_workshop,
    revoke_other_sessions,
    revoke_session,
)
from app.modules.access.telegram_bot import handle_update as handle_telegram_update
from app.modules.access.telegram_login import (
    ClientLoginResult,
    LoginPollResult,
    LoginTokenIssue,
    create_login_token,
    dev_confirm_login_token,
    hash_login_code,
    hash_login_token,
    issue_login_code,
    poll_login_token,
    prune_expired_telegram_logins,
    redeem_login_code,
)

__all__ = [
    "ACCESS_TTL",
    "INVALID_CREDENTIALS_CODE",
    "MAX_SESSIONS_PER_PRINCIPAL",
    "REFRESH_TTL",
    "AuthSessionResult",
    "BranchScope",
    "ClientLoginResult",
    "ClientResolution",
    "LoginIpThrottle",
    "LoginPollResult",
    "LoginTokenIssue",
    "PlainSessionTokens",
    "SlidingWindowIpThrottle",
    "authenticate_platform_user",
    "authenticate_workshop_user",
    "can_access_branch",
    "change_password",
    "create_login_token",
    "create_session",
    "dev_confirm_login_token",
    "find_or_create_client",
    "get_session_by_access_token",
    "get_session_by_refresh_token",
    "handle_telegram_update",
    "hash_login_code",
    "hash_login_token",
    "issue_login_code",
    "login_throttle",
    "normalize_uz_phone",
    "pin_branch_on_order",
    "poll_login_token",
    "principal_from_session",
    "prune_expired_sessions",
    "prune_expired_telegram_logins",
    "redeem_login_code",
    "refresh_session",
    "require_manage_orders_workshop",
    "resolve_branch_scope",
    "resolve_branch_scope_any",
    "resolve_client_ip",
    "revoke_for_principal",
    "revoke_for_workshop",
    "revoke_other_sessions",
    "revoke_session",
    "telegram_code_throttle",
    "visible_branch_ids",
    "visible_workshop_ids",
]
