"""Public access API used by routes and other modules."""

from app.modules.access.auth import (
    AuthSessionResult,
    authenticate_platform_user,
    authenticate_workshop_user,
    change_password,
)
from app.modules.access.authz import (
    BranchScope,
    can_access_branch,
    require_manage_orders_workshop,
    resolve_branch_scope,
    visible_branch_ids,
    visible_workshop_ids,
)
from app.modules.access.clients import (
    ClientResolution,
    find_or_create_client,
    normalize_uz_phone,
)
from app.modules.access.otp import (
    ClientOtpLoginResult,
    ClientOtpVerifyResult,
    OtpRequestResult,
    OtpSender,
    TelegramDeliveryError,
    TelegramGatewaySender,
    hash_otp_code,
    request_otp_code,
    resolve_client_ip,
    verify_otp_code,
)
from app.modules.access.sessions import (
    ACCESS_TTL,
    MAX_SESSIONS_PER_PRINCIPAL,
    REFRESH_TTL,
    PlainSessionTokens,
    create_session,
    get_session_by_access_token,
    get_session_by_refresh_token,
    principal_from_session,
    prune_expired_sessions,
    refresh_session,
    revoke_for_principal,
    revoke_for_workshop,
    revoke_other_sessions,
    revoke_session,
)

__all__ = [
    "ACCESS_TTL",
    "MAX_SESSIONS_PER_PRINCIPAL",
    "REFRESH_TTL",
    "AuthSessionResult",
    "BranchScope",
    "ClientOtpLoginResult",
    "ClientOtpVerifyResult",
    "ClientResolution",
    "OtpRequestResult",
    "OtpSender",
    "PlainSessionTokens",
    "TelegramDeliveryError",
    "TelegramGatewaySender",
    "authenticate_platform_user",
    "authenticate_workshop_user",
    "can_access_branch",
    "change_password",
    "create_session",
    "find_or_create_client",
    "get_session_by_access_token",
    "get_session_by_refresh_token",
    "hash_otp_code",
    "normalize_uz_phone",
    "principal_from_session",
    "prune_expired_sessions",
    "refresh_session",
    "request_otp_code",
    "require_manage_orders_workshop",
    "resolve_branch_scope",
    "resolve_client_ip",
    "revoke_for_principal",
    "revoke_for_workshop",
    "revoke_other_sessions",
    "revoke_session",
    "verify_otp_code",
    "visible_branch_ids",
    "visible_workshop_ids",
]
