import type { RouteRecordRaw } from 'vue-router'

export const workshopRoutes: RouteRecordRaw[] = [
  {
    path: '/',
    redirect: '/workshop',
  },
  {
    path: '/auth/login',
    name: 'workshop-login',
    component: () => import('@/shared/views/LoginView.vue'),
    meta: { layout: 'auth', title: 'Kirish' },
  },
  {
    path: '/workshop',
    name: 'workshop-home',
    component: () => import('@/shared/views/WorkshopDashboardView.vue'),
    meta: { title: 'Asosiy' },
  },
  {
    path: '/workshop/profile',
    name: 'workshop-profile',
    component: () => import('@/shared/views/ProfileView.vue'),
    meta: { title: 'Mening profilim' },
  },
  {
    path: '/workshop/orders',
    name: 'workshop-orders',
    component: () => import('@/shared/views/WorkshopOrdersView.vue'),
    meta: { title: 'Buyurtmalar' },
  },
  {
    path: '/workshop/orders/:order_id',
    name: 'workshop-order-detail',
    component: () => import('@/shared/views/WorkshopOrderDetailView.vue'),
    meta: { title: 'Buyurtma tafsilotlari' },
  },
  {
    path: '/workshop/cutting',
    name: 'workshop-cutting-queue',
    component: () => import('@/shared/views/WorkshopCuttingQueueView.vue'),
    meta: { title: 'Kesish navbati' },
  },
  {
    path: '/workshop/banding',
    name: 'workshop-banding-queue',
    component: () => import('@/shared/views/WorkshopBandingQueueView.vue'),
    meta: { title: 'Krom navbati' },
  },
  {
    path: '/workshop/inventory',
    name: 'workshop-inventory',
    component: () => import('@/shared/views/WorkshopInventoryView.vue'),
    meta: { title: 'Ombor' },
  },
  {
    path: '/workshop/catalog',
    name: 'workshop-catalog',
    component: () => import('@/shared/views/WorkshopCatalogView.vue'),
    meta: { title: 'Material katalogi' },
  },
  {
    path: '/workshop/settings/users',
    name: 'workshop-users',
    component: () => import('@/shared/views/WorkshopUsersView.vue'),
    meta: { title: 'Xodimlar' },
  },
  {
    path: '/workshop/settings',
    name: 'workshop-settings',
    component: () => import('@/shared/views/WorkshopSettingsView.vue'),
    meta: { title: 'Sozlamalar' },
  },
  {
    path: '/workshop/branches',
    name: 'workshop-branches',
    component: () => import('@/shared/views/WorkshopBranchesView.vue'),
    meta: { title: 'Filiallar' },
  },
  {
    path: '/workshop/branches/:branch_id',
    name: 'workshop-branch-detail',
    component: () => import('@/shared/views/WorkshopBranchDetailView.vue'),
    meta: { title: 'Filial tafsilotlari' },
  },
  {
    path: '/workshop/cutting-plans',
    name: 'workshop-cutting-plans',
    component: () => import('@/shared/views/WorkshopCuttingPlansView.vue'),
    meta: { title: 'Kesim rejalar' },
  },
  {
    path: '/workshop/finance',
    name: 'workshop-finance',
    component: () => import('@/shared/views/WorkshopFinanceView.vue'),
    meta: { title: 'Hisobotlar' },
  },
  {
    path: '/workshop/finance/income',
    name: 'workshop-finance-income',
    component: () => import('@/shared/views/WorkshopFinanceExpensesView.vue'),
    meta: { title: 'Tushum' },
  },
  {
    path: '/workshop/finance/expenses',
    name: 'workshop-finance-expenses',
    component: () => import('@/shared/views/WorkshopFinanceExpensesView.vue'),
    meta: { title: 'Tushum va xarajat' },
  },
  {
    path: '/workshop/finance/production',
    name: 'workshop-finance-production',
    component: () => import('@/shared/views/WorkshopFinanceProductionView.vue'),
    meta: { title: 'Ishlab chiqarish hisobotlari' },
  },
  {
    path: '/workshop/cutting-plans/:result_id',
    name: 'workshop-cutting-plan-detail',
    component: () => import('@/shared/views/WorkshopCuttingPlanDetailView.vue'),
    meta: { title: 'Kesim reja tafsilotlari' },
  },
  {
    path: '/workshop/settings/users/:user_id',
    name: 'workshop-user-detail',
    component: () => import('@/shared/views/WorkshopUserDetailView.vue'),
    meta: { title: 'Xodim tafsilotlari' },
  },
  {
    path: '/workshop/notifications',
    name: 'workshop-notifications',
    component: () => import('@/shared/views/WorkshopNotificationsView.vue'),
    meta: { title: 'Bildirishnomalar' },
  },
  {
    path: '/:pathMatch(.*)*',
    name: 'workshop-not-found',
    component: () => import('@/shared/views/RoleNotFoundView.vue'),
    meta: { title: 'Sahifa topilmadi' },
  },
]
