"""Public cutting API used by other modules."""

from app.modules.cutting.imports import parse_import_file
from app.modules.cutting.optimizer import (
    ALGORITHM_VERSION,
    EDGE_OVERHANG_MM,
    EDGE_TRIM_MM,
    KERF_MM,
    MAX_PANELS_PER_MATERIAL,
    MAX_PARTS_PER_RUN,
    OPTIMIZATION_TIMEOUT_SECONDS,
    EdgeBandInput,
    OffcutResult,
    OptimizationResult,
    OptimizerError,
    PanelResult,
    PanelSpec,
    PartInput,
    PlacementResult,
    run_all_algorithms,
)
from app.modules.cutting.rendering import render_cutting_pdf, render_cutting_svg
from app.modules.cutting.service import (
    choose_result,
    client_catalog_materials,
    commit_imported_map,
    create_draft,
    cutting_result_response,
    delete_draft,
    get_client_result,
    get_draft,
    list_drafts,
    optimize_draft,
    update_draft,
)
from app.modules.cutting.workshop_service import (
    choose_workshop_result,
    create_workshop_draft,
    delete_workshop_draft,
    get_workshop_draft,
    get_workshop_result,
    optimize_workshop_draft,
    update_workshop_draft,
    workshop_catalog_materials,
)

__all__ = [
    "ALGORITHM_VERSION",
    "EDGE_OVERHANG_MM",
    "EDGE_TRIM_MM",
    "KERF_MM",
    "MAX_PANELS_PER_MATERIAL",
    "MAX_PARTS_PER_RUN",
    "OPTIMIZATION_TIMEOUT_SECONDS",
    "EdgeBandInput",
    "OffcutResult",
    "OptimizationResult",
    "OptimizerError",
    "PanelResult",
    "PanelSpec",
    "PartInput",
    "PlacementResult",
    "choose_result",
    "choose_workshop_result",
    "client_catalog_materials",
    "commit_imported_map",
    "create_draft",
    "create_workshop_draft",
    "cutting_result_response",
    "delete_draft",
    "delete_workshop_draft",
    "get_client_result",
    "get_draft",
    "get_workshop_draft",
    "get_workshop_result",
    "list_drafts",
    "optimize_draft",
    "optimize_workshop_draft",
    "parse_import_file",
    "render_cutting_pdf",
    "render_cutting_svg",
    "run_all_algorithms",
    "update_draft",
    "update_workshop_draft",
    "workshop_catalog_materials",
]
