"""initial foundation schema

Revision ID: 2d7f9d06216e
Revises:
Create Date: 2026-06-02 22:34:10.362464
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "2d7f9d06216e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

POSTGRES_ENUM_TYPES = (
    "actor_type",
    "authenticated_principal_type",
    "user_status",
    "workshop_status",
    "branch_status",
    "permission",
    "material_status",
    "material_kind",
    "panel_material_type",
    "stock_transaction_type",
    "supplier_status",
    "material_source",
    "cutting_result_status",
    "order_status",
    "currency",
    "income_type",
    "money_method",
    "ledger_status",
    "expense_category",
    "file_storage_status",
    "job_run_status",
    "error_record_status",
)


def _create_functional_indexes() -> None:
    op.create_index(
        "uq_manufacturers_name_ci",
        "manufacturers",
        [sa.text("lower(name)")],
        unique=True,
    )
    op.create_index(
        "uq_platform_users_login_ci",
        "platform_users",
        [sa.text("lower(login)")],
        unique=True,
    )
    op.create_index(
        "uq_workshops_code_ci",
        "workshops",
        [sa.text("lower(code)")],
        unique=True,
    )
    op.create_index(
        "uq_workshop_users_workshop_login_ci",
        "workshop_users",
        ["workshop_id", sa.text("lower(login)")],
        unique=True,
    )


def _create_deferred_foreign_keys() -> None:
    if op.get_bind().dialect.name == "sqlite":
        return
    op.create_foreign_key(
        "fk_workshops_owner_user",
        "workshops",
        "workshop_users",
        ["owner_user_id", "id"],
        ["id", "workshop_id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_cutting_drafts_chosen_result_id",
        "cutting_drafts",
        "cutting_results",
        ["chosen_result_id"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_orders_cutting_result_id",
        "orders",
        "cutting_results",
        ["cutting_result_id"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )
    op.create_foreign_key(
        "fk_cutting_results_order_id",
        "cutting_results",
        "orders",
        ["order_id"],
        ["id"],
        deferrable=True,
        initially="DEFERRED",
    )


def _drop_deferred_foreign_keys() -> None:
    if op.get_bind().dialect.name == "sqlite":
        return
    op.drop_constraint("fk_cutting_results_order_id", "cutting_results", type_="foreignkey")
    op.drop_constraint("fk_orders_cutting_result_id", "orders", type_="foreignkey")
    op.drop_constraint("fk_cutting_drafts_chosen_result_id", "cutting_drafts", type_="foreignkey")
    op.drop_constraint("fk_workshops_owner_user", "workshops", type_="foreignkey")


def _drop_functional_indexes() -> None:
    op.drop_index("uq_workshop_users_workshop_login_ci", table_name="workshop_users")
    op.drop_index("uq_workshops_code_ci", table_name="workshops")
    op.drop_index("uq_platform_users_login_ci", table_name="platform_users")
    op.drop_index("uq_manufacturers_name_ci", table_name="manufacturers")


def _drop_postgres_enum_types() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for enum_name in reversed(POSTGRES_ENUM_TYPES):
        op.execute(sa.text(f'DROP TYPE IF EXISTS "{enum_name}"'))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "storage_status",
            sa.Enum(
                "pending", "stored", "deleted", name="file_storage_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_by_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                name="authenticated_principal_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("size_bytes >= 0", name="ck_files_size_nonnegative"),
        sa.CheckConstraint("sort_order IS NULL OR sort_order >= 0", name="ck_files_sort_order"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_table(
        "job_definitions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("schedule", sa.String(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("running", sa.Boolean(), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_result",
            sa.Enum(
                "running", "ok", "failed", "skipped", name="job_run_status", create_constraint=True
            ),
            nullable=True,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_job_definitions_name"),
    )
    op.create_table(
        "manufacturers",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="material_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column(
            "recipient_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                name="authenticated_principal_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("event_code", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notifications_recipient_unread",
        "notifications",
        ["recipient_type", "recipient_id", "read_at"],
        unique=False,
    )
    op.create_table(
        "phone_verification_challenges",
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("code_hash", sa.String(), nullable=False),
        sa.Column("request_ip", sa.String(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "attempt_count >= 0 AND attempt_count <= 5", name="ck_phone_challenges_attempts"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_phone_verification_challenges_phone"),
        "phone_verification_challenges",
        ["phone"],
        unique=False,
    )
    op.create_index(
        op.f("ix_phone_verification_challenges_request_ip"),
        "phone_verification_challenges",
        ["request_ip"],
        unique=False,
    )
    op.create_table(
        "platform_users",
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="user_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("password_reset_required", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "sessions",
        sa.Column(
            "principal_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                name="authenticated_principal_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_hash", sa.String(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "device_info",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token_hash", name="uq_sessions_access_token_hash"),
        sa.UniqueConstraint("refresh_token_hash", name="uq_sessions_refresh_token_hash"),
    )
    op.create_index(
        "ix_sessions_principal", "sessions", ["principal_type", "principal_id"], unique=False
    )
    op.create_table(
        "error_records",
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("module", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", name="error_record_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("count_24h", sa.Integer(), nullable=False),
        sa.Column("count_7d", sa.Integer(), nullable=False),
        sa.Column("last_occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("preview_message", sa.String(), nullable=True),
        sa.Column("resolved_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("count_24h >= 0 AND count_7d >= 0", name="ck_error_records_counts"),
        sa.ForeignKeyConstraint(
            ["resolved_by_user_id"],
            ["platform_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_error_records_code"),
    )
    op.create_table(
        "job_runs",
        sa.Column("job_definition_id", sa.Uuid(), nullable=True),
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "running", "ok", "failed", "skipped", name="job_run_status", create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("brief_log", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("trace_id", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_definition_id"],
            ["job_definitions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_job_runs_job_started", "job_runs", ["job_name", "started_at"], unique=False)
    op.create_table(
        "materials",
        sa.Column(
            "kind",
            sa.Enum("panel", "edge", name="material_kind", create_constraint=True),
            nullable=False,
        ),
        sa.Column("manufacturer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "dsp",
                "mdf",
                "plywood",
                "natural_wood",
                "other",
                name="panel_material_type",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("thickness_mm", sa.Numeric(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("decor_code", sa.String(), nullable=True),
        sa.Column("panel_length_mm", sa.Integer(), nullable=True),
        sa.Column("panel_width_mm", sa.Integer(), nullable=True),
        sa.Column("grain_direction", sa.Boolean(), nullable=True),
        sa.Column("image_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="material_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(kind = 'panel' AND type IS NOT NULL AND panel_length_mm IS NOT NULL AND panel_width_mm IS NOT NULL AND panel_length_mm >= panel_width_mm AND grain_direction IS NOT NULL) OR (kind = 'edge' AND type IS NULL AND panel_length_mm IS NULL AND panel_width_mm IS NULL AND grain_direction IS NULL)",
            name="ck_materials_kind_shape",
        ),
        sa.CheckConstraint("thickness_mm > 0", name="ck_materials_thickness_positive"),
        sa.ForeignKeyConstraint(
            ["image_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["manufacturer_id"],
            ["manufacturers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "workshops",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("logo_file_id", sa.Uuid(), nullable=True),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="workshop_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "currency", sa.Enum("UZS", name="currency", create_constraint=True), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["logo_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_user_id", "id"],
            ["workshop_users.id", "workshop_users.workshop_id"],
            name="fk_workshops_owner_user",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branches",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("latitude", sa.Numeric(), nullable=False),
        sa.Column("longitude", sa.Numeric(), nullable=False),
        sa.Column(
            "working_hours",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "temporarily_closed",
                "inactive",
                name="branch_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("closed_reason", sa.String(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="ck_branches_latitude"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180", name="ck_branches_longitude"),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "error_occurrences",
        sa.Column("error_record_id", sa.Uuid(), nullable=False),
        sa.Column("trace_id", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("stack", sa.String(), nullable=True),
        sa.Column(
            "context",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["error_record_id"],
            ["error_records.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_error_occurrences_record_time",
        "error_occurrences",
        ["error_record_id", "occurred_at"],
        unique=False,
    )
    op.create_table(
        "branch_materials",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="material_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("min_stock >= 0", name="ck_branch_materials_min_stock_nonnegative"),
        sa.CheckConstraint("price_tiyin >= 0", name="ck_branch_materials_price_nonnegative"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "material_id", name="uq_branch_materials_branch_material"),
    )
    op.create_table(
        "clients",
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("preferred_branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="user_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("length(name) >= 1 AND length(name) <= 80", name="ck_clients_name_len"),
        sa.ForeignKeyConstraint(
            ["preferred_branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone", name="uq_clients_phone"),
    )
    op.create_table(
        "stock_items",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("min_stock >= 0", name="ck_stock_items_min_stock_nonnegative"),
        sa.CheckConstraint("on_hand >= 0", name="ck_stock_items_on_hand_nonnegative"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "material_id", name="uq_stock_items_branch_material"),
    )
    op.create_table(
        "workshop_users",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("login", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("home_branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "blocked", name="user_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("password_reset_required", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["home_branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "workshop_id", name="uq_workshop_users_id_workshop"),
    )
    op.create_index(
        "uq_workshop_users_one_owner_per_workshop",
        "workshop_users",
        ["workshop_id"],
        unique=True,
        postgresql_where=sa.text("is_owner = true"),
        sqlite_where=sa.text("is_owner = 1"),
    )
    op.create_table(
        "action_logs",
        sa.Column(
            "actor_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                "system",
                name="actor_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("entity_type", sa.String(), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.String(), nullable=True),
        sa.Column(
            "details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("trace_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_action_logs_entity", "action_logs", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_action_logs_workshop_branch", "action_logs", ["workshop_id", "branch_id"], unique=False
    )
    op.create_table(
        "branch_pricing",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("cutting_rate_tiyin", sa.BigInteger(), nullable=True),
        sa.Column("edge_banding_rate_tiyin", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint(
            "cutting_rate_tiyin IS NULL OR cutting_rate_tiyin >= 0",
            name="ck_branch_pricing_cutting_nonnegative",
        ),
        sa.CheckConstraint(
            "edge_banding_rate_tiyin IS NULL OR edge_banding_rate_tiyin >= 0",
            name="ck_branch_pricing_edge_nonnegative",
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.PrimaryKeyConstraint("branch_id"),
    )
    op.create_table(
        "cutting_drafts",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "parts_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("chosen_result_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["chosen_result_id"],
            ["cutting_results.id"],
            name="fk_cutting_drafts_chosen_result_id",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["preferred_branch_id"],
            ["branches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "expenses",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "rent",
                "utilities",
                "raw_materials",
                "supplies",
                "transport",
                "equipment",
                "marketing",
                "taxes_and_fees",
                "salary",
                "other",
                name="expense_category",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("amount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("incurred_on", sa.Date(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("vendor", sa.String(), nullable=True),
        sa.Column("receipt_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("recorded", "voided", name="ledger_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("voided_reason", sa.String(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("amount_tiyin > 0", name="ck_expenses_amount_positive"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("order_number", sa.String(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("cutting_result_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "confirmed",
                "cutting",
                "edge_banding",
                "ready",
                "completed",
                "cancelled",
                name="order_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("contact_name", sa.String(), nullable=False),
        sa.Column("contact_phone", sa.String(), nullable=False),
        sa.Column("note_client", sa.String(), nullable=True),
        sa.Column("note_workshop", sa.String(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subtotal_cutting_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_materials_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_edge_banding_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("discount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("discount_reason", sa.String(), nullable=True),
        sa.Column("discount_applied_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("total_tiyin", sa.BigInteger(), nullable=False),
        sa.Column(
            "currency", sa.Enum("UZS", name="currency", create_constraint=True), nullable=False
        ),
        sa.Column("assigned_cutter_user_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_edger_user_id", sa.Uuid(), nullable=True),
        sa.Column("cutter_user_id", sa.Uuid(), nullable=True),
        sa.Column("cut_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("panels_used_snapshot", sa.Integer(), nullable=True),
        sa.Column("cut_count_snapshot", sa.Integer(), nullable=True),
        sa.Column("edger_user_id", sa.Uuid(), nullable=True),
        sa.Column("edge_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "edge_length_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint("discount_tiyin >= 0", name="ck_orders_discount_nonnegative"),
        sa.CheckConstraint(
            "discount_tiyin = 0 OR (discount_reason IS NOT NULL AND discount_applied_by_user_id IS NOT NULL)",
            name="ck_orders_discount_metadata_required",
        ),
        sa.CheckConstraint(
            "discount_tiyin <= (subtotal_cutting_tiyin + subtotal_materials_tiyin + subtotal_edge_banding_tiyin)",
            name="ck_orders_discount_not_above_subtotal",
        ),
        sa.CheckConstraint("subtotal_cutting_tiyin >= 0", name="ck_orders_cutting_nonnegative"),
        sa.CheckConstraint("subtotal_edge_banding_tiyin >= 0", name="ck_orders_edge_nonnegative"),
        sa.CheckConstraint("subtotal_materials_tiyin >= 0", name="ck_orders_materials_nonnegative"),
        sa.CheckConstraint(
            "total_tiyin = (subtotal_cutting_tiyin + subtotal_materials_tiyin + subtotal_edge_banding_tiyin - discount_tiyin)",
            name="ck_orders_total_formula",
        ),
        sa.CheckConstraint("total_tiyin >= 0", name="ck_orders_total_nonnegative"),
        sa.CheckConstraint("version >= 1", name="ck_orders_version_positive"),
        sa.ForeignKeyConstraint(
            ["assigned_cutter_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["assigned_edger_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cutter_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["cutting_result_id"],
            ["cutting_results.id"],
            name="fk_orders_cutting_result_id",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.ForeignKeyConstraint(
            ["discount_applied_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["edger_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cutting_result_id", name="uq_orders_cutting_result"),
        sa.UniqueConstraint("order_number", name="uq_orders_order_number"),
    )
    op.create_table(
        "permission_grants",
        sa.Column("workshop_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum(
                "view_dashboard",
                "manage_orders",
                "process_production",
                "manage_catalog",
                "manage_inventory",
                "manage_finance",
                "view_finance_reports",
                name="permission",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("granted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["workshop_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workshop_user_id",
            "permission",
            "branch_id",
            name="uq_permission_grants_user_permission_branch",
        ),
    )
    op.create_table(
        "suppliers",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="supplier_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cutting_results",
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("algorithm_name", sa.String(), nullable=False),
        sa.Column("algorithm_version", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "candidate",
                "confirmed",
                "invalidated",
                name="cutting_result_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("kerf_mm", sa.Integer(), nullable=False),
        sa.Column("edge_trim_mm", sa.Integer(), nullable=False),
        sa.Column(
            "panels_used_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("waste_percentage", sa.Numeric(), nullable=False),
        sa.Column("total_cut_length_mm", sa.Integer(), nullable=False),
        sa.Column("total_edge_length_mm", sa.Integer(), nullable=False),
        sa.Column(
            "edge_length_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "parts_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "material_snapshots",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "edge_length_shop_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "edge_length_own_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "edge_consumed_shop_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "edge_consumed_own_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "edge_banded_sides_by_material",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("total_cut_length_mm >= 0", name="ck_cutting_results_cut_length"),
        sa.CheckConstraint("total_edge_length_mm >= 0", name="ck_cutting_results_edge_length"),
        sa.CheckConstraint(
            "waste_percentage >= 0 AND waste_percentage <= 1", name="ck_cutting_results_waste"
        ),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["cutting_drafts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name="fk_cutting_results_order_id",
            initially="DEFERRED",
            deferrable=True,
            use_alter=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_cutting_results_order"),
    )
    op.create_table(
        "incomes",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("order_payment", "other", name="income_type", create_constraint=True),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("amount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column(
            "method",
            sa.Enum("cash", "bank_transfer", "other", name="money_method", create_constraint=True),
            nullable=False,
        ),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("receipt_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("recorded", "voided", name="ledger_status", create_constraint=True),
            nullable=False,
        ),
        sa.Column("voided_reason", sa.String(), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type = 'order_payment' AND order_id IS NOT NULL) OR (type <> 'order_payment' AND order_id IS NULL)",
            name="ck_incomes_order_required_for_order_payment",
        ),
        sa.CheckConstraint("amount_tiyin > 0", name="ck_incomes_amount_positive"),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voided_by_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_cancellations",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "cancelled_by_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                "system",
                name="actor_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("cancelled_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_by_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(), nullable=False),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "((cancelled_by_type = 'client' AND cancelled_by_client_id IS NOT NULL AND cancelled_by_user_id IS NULL) OR (cancelled_by_type = 'workshop_user' AND cancelled_by_user_id IS NOT NULL AND cancelled_by_client_id IS NULL))",
            name="ck_order_cancellations_actor_shape",
        ),
        sa.ForeignKeyConstraint(
            ["cancelled_by_client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id", name="uq_order_cancellations_order"),
    )
    op.create_table(
        "order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "material_source",
            sa.Enum("shop", "own", name="material_source", create_constraint=True),
            nullable=False,
        ),
        sa.Column(
            "material_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("part_ref", sa.String(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "edge_top",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "edge_bottom",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "edge_left",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "edge_right",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("unit_cutting_price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("unit_material_price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("edge_cost_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("line_total_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("edge_cost_tiyin >= 0", name="ck_order_items_edge_cost"),
        sa.CheckConstraint("length_mm > 0 AND width_mm > 0", name="ck_order_items_dimensions"),
        sa.CheckConstraint(
            "line_total_tiyin = ((unit_cutting_price_tiyin + unit_material_price_tiyin) * quantity + edge_cost_tiyin)",
            name="ck_order_items_line_total_formula",
        ),
        sa.CheckConstraint("line_total_tiyin >= 0", name="ck_order_items_line_total"),
        sa.CheckConstraint("quantity >= 1", name="ck_order_items_quantity"),
        sa.CheckConstraint("unit_cutting_price_tiyin >= 0", name="ck_order_items_cutting_price"),
        sa.CheckConstraint("unit_material_price_tiyin >= 0", name="ck_order_items_material_price"),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "order_status_events",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "new",
                "confirmed",
                "cutting",
                "edge_banding",
                "ready",
                "completed",
                "cancelled",
                name="order_status",
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "new",
                "confirmed",
                "cutting",
                "edge_banding",
                "ready",
                "completed",
                "cancelled",
                name="order_status",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                "system",
                name="actor_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column(
            "metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "((actor_type = 'client' AND actor_client_id IS NOT NULL AND actor_user_id IS NULL) OR (actor_type = 'workshop_user' AND actor_user_id IS NOT NULL AND actor_client_id IS NULL) OR (actor_type = 'system' AND actor_user_id IS NULL AND actor_client_id IS NULL))",
            name="ck_order_status_events_actor_shape",
        ),
        sa.ForeignKeyConstraint(
            ["actor_client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "status_change_logs",
        sa.Column("entity_type", sa.String(), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("from_status", sa.String(), nullable=True),
        sa.Column("to_status", sa.String(), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "platform_user",
                "workshop_user",
                "client",
                "system",
                name="actor_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(), nullable=True),
        sa.Column("action_log_id", sa.Uuid(), nullable=True),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_log_id"],
            ["action_logs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["actor_client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshops.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_change_logs_entity",
        "status_change_logs",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index(
        "ix_status_change_logs_workshop_branch",
        "status_change_logs",
        ["workshop_id", "branch_id"],
        unique=False,
    )
    op.create_table(
        "stock_transactions",
        sa.Column("stock_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "stock_in",
                "consume",
                "restore",
                "adjust",
                name="stock_transaction_type",
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("receipt_file_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("balance_after >= 0", name="ck_stock_transactions_balance_nonnegative"),
        sa.CheckConstraint("quantity <> 0", name="ck_stock_transactions_quantity_nonzero"),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["workshop_users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["receipt_file_id"],
            ["files.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stock_item_id"],
            ["stock_items.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cutting_panels",
        sa.Column("cutting_result_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("panel_index", sa.Integer(), nullable=False),
        sa.Column("waste_area_mm2", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("panel_index >= 1", name="ck_cutting_panels_index_positive"),
        sa.CheckConstraint("waste_area_mm2 >= 0", name="ck_cutting_panels_waste_nonnegative"),
        sa.ForeignKeyConstraint(
            ["cutting_result_id"],
            ["cutting_results.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "cutting_result_id",
            "material_id",
            "panel_index",
            name="uq_cutting_panels_result_material_index",
        ),
    )
    op.create_table(
        "cutting_placements",
        sa.Column("cutting_panel_id", sa.Uuid(), nullable=False),
        sa.Column("part_ref", sa.String(), nullable=False),
        sa.Column("part_quantity_index", sa.Integer(), nullable=False),
        sa.Column("x_mm", sa.Integer(), nullable=False),
        sa.Column("y_mm", sa.Integer(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("rotated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("length_mm > 0 AND width_mm > 0", name="ck_cutting_placements_size"),
        sa.CheckConstraint("part_quantity_index >= 1", name="ck_cutting_placements_quantity_index"),
        sa.CheckConstraint("x_mm >= 0 AND y_mm >= 0", name="ck_cutting_placements_origin"),
        sa.ForeignKeyConstraint(
            ["cutting_panel_id"],
            ["cutting_panels.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    _create_deferred_foreign_keys()
    _create_functional_indexes()
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_deferred_foreign_keys()
    op.drop_table("cutting_placements")
    op.drop_table("cutting_panels")
    op.drop_table("stock_transactions")
    op.drop_index("ix_status_change_logs_workshop_branch", table_name="status_change_logs")
    op.drop_index("ix_status_change_logs_entity", table_name="status_change_logs")
    op.drop_table("status_change_logs")
    op.drop_table("order_status_events")
    op.drop_table("order_items")
    op.drop_table("order_cancellations")
    op.drop_table("incomes")
    op.drop_table("cutting_results")
    op.drop_table("suppliers")
    op.drop_table("permission_grants")
    op.drop_table("orders")
    op.drop_table("expenses")
    op.drop_table("cutting_drafts")
    op.drop_table("branch_pricing")
    op.drop_index("ix_action_logs_workshop_branch", table_name="action_logs")
    op.drop_index("ix_action_logs_entity", table_name="action_logs")
    op.drop_table("action_logs")
    op.drop_index(
        "uq_workshop_users_one_owner_per_workshop",
        table_name="workshop_users",
    )
    _drop_functional_indexes()
    op.drop_table("workshop_users")
    op.drop_table("stock_items")
    op.drop_table("clients")
    op.drop_table("branch_materials")
    op.drop_index("ix_error_occurrences_record_time", table_name="error_occurrences")
    op.drop_table("error_occurrences")
    op.drop_table("branches")
    op.drop_table("workshops")
    op.drop_table("materials")
    op.drop_index("ix_job_runs_job_started", table_name="job_runs")
    op.drop_table("job_runs")
    op.drop_table("error_records")
    op.drop_index("ix_sessions_principal", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("platform_users")
    op.drop_index(
        op.f("ix_phone_verification_challenges_request_ip"),
        table_name="phone_verification_challenges",
    )
    op.drop_index(
        op.f("ix_phone_verification_challenges_phone"), table_name="phone_verification_challenges"
    )
    op.drop_table("phone_verification_challenges")
    op.drop_index("ix_notifications_recipient_unread", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("manufacturers")
    op.drop_table("job_definitions")
    op.drop_table("files")
    _drop_postgres_enum_types()
    # ### end Alembic commands ###
