"""per-branch kerf and edge trim

Revision ID: 37ee5335706c
Revises: c2d3e4f5a6b7
Create Date: 2026-07-25 03:36:23.354739
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "37ee5335706c"
down_revision: str | None = "c2d3e4f5a6b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "branches", sa.Column("kerf_mm", sa.Integer(), server_default="4", nullable=False)
    )
    op.add_column(
        "branches", sa.Column("edge_trim_mm", sa.Integer(), server_default="5", nullable=False)
    )
    # ### end Alembic commands ###
    # Autogenerate misses CheckConstraints — added by hand (backend/AGENTS.md).
    op.create_check_constraint("ck_branches_kerf_mm", "branches", "kerf_mm >= 1 AND kerf_mm <= 20")
    op.create_check_constraint(
        "ck_branches_edge_trim_mm", "branches", "edge_trim_mm >= 0 AND edge_trim_mm <= 50"
    )


def downgrade() -> None:
    op.drop_constraint("ck_branches_edge_trim_mm", "branches", type_="check")
    op.drop_constraint("ck_branches_kerf_mm", "branches", type_="check")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("branches", "edge_trim_mm")
    op.drop_column("branches", "kerf_mm")
    # ### end Alembic commands ###
