"""add order draft name and workshop origin

Revision ID: b06a71097c10
Revises: 332b3473dfe4
Create Date: 2026-07-30 21:54:45.615896
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b06a71097c10"
down_revision: str | None = "332b3473dfe4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("orders", sa.Column("draft_name", sa.String(), nullable=True))
    op.add_column(
        "orders",
        sa.Column(
            "created_via_workshop", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "created_via_workshop")
    op.drop_column("orders", "draft_name")
    # ### end Alembic commands ###
