"""Customer-supplied boards: sheets a walk-in brings that the branch does not sell.

Five columns on `branch_materials`, a partial unique index, and one seeded
manufacturer + dekor the boards all point at.

The index change is the load-bearing part. `uq_branch_materials_branch_dekor_format`
says a branch carries one row per (dekor, format). Every customer board points at
the single seeded `Mijoz` dekor, so two walk-ins bringing 2750x1830x16 to the same
branch produce an identical tuple and the second insert would be rejected. The
predicate scopes uniqueness to rows the branch actually carries, which is what the
constraint always meant.

Hand-written, not autogenerated: autogenerate emits the `add_column` calls and
nothing else — not the index predicate, not the seed.
"""

import uuid
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from app.core.search_fold import fold

# revision identifiers, used by Alembic.
revision: str = "d4b18e6c07a9"
down_revision: str | None = "8a41c7b0d5e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Fixed ids so the seed is idempotent across environments and so application
# code can reference the dekor without a name lookup.
CUSTOMER_MANUFACTURER_ID = uuid.UUID("00000000-0000-0000-0000-00000000c001")
CUSTOMER_DEKOR_ID = uuid.UUID("00000000-0000-0000-0000-00000000c002")
CUSTOMER_MANUFACTURER_NAME = "Mijoz"
# Reads as one phrase after the manufacturer: "List Mijoz materiali".
# "Mijoz listi" here would render "List Mijoz Mijoz listi".
CUSTOMER_DEKOR_NAME = "materiali"

_INDEX = "uq_branch_materials_branch_dekor_format"


def upgrade() -> None:
    op.add_column(
        "branch_materials",
        sa.Column(
            "customer_supplied",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        ),
    )
    op.add_column("branch_materials", sa.Column("nomi", sa.String(), nullable=True))
    op.add_column("branch_materials", sa.Column("tolali", sa.Boolean(), nullable=True))
    op.add_column(
        "branch_materials",
        sa.Column("source_draft_id", sa.Uuid(), nullable=True),
    )
    op.add_column(
        "branch_materials",
        sa.Column("stock_material_id", sa.Uuid(), nullable=True),
    )
    op.create_foreign_key(
        "fk_branch_materials_source_draft",
        "branch_materials",
        "cutting_drafts",
        ["source_draft_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_branch_materials_stock_material",
        "branch_materials",
        "branch_materials",
        ["stock_material_id"],
        ["id"],
    )
    op.create_index(
        "ix_branch_materials_source_draft",
        "branch_materials",
        ["source_draft_id"],
    )

    op.drop_index(_INDEX, table_name="branch_materials")
    op.create_index(
        _INDEX,
        "branch_materials",
        [
            "branch_id",
            "dekor_id",
            "qalinlik_mm",
            sa.text("coalesce(uzunlik_mm, 0)"),
            sa.text("coalesce(eni_mm, 0)"),
            sa.text("coalesce(kromka_eni_mm, 0)"),
        ],
        unique=True,
        postgresql_where=sa.text("NOT customer_supplied"),
    )

    _seed_customer_dekor()


def _seed_customer_dekor() -> None:
    """One manufacturer + one dekor every customer board points at.

    `ON CONFLICT DO NOTHING` rather than a existence check: the ids are fixed, so
    a re-run is a no-op, and the name indexes are case-insensitive expressions a
    plain SELECT would have to reproduce.

    `search_key` is folded with the same function the service layer uses, so a
    row written here and a row written by the API agree — the coupling note in
    `c9f4a2b71e83` applies here too.
    """
    bind = op.get_bind()
    bind.execute(
        sa.text(
            """
            INSERT INTO manufacturers (id, name, country, note, status)
            VALUES (:id, :name, NULL, NULL, CAST('active' AS material_status))
            ON CONFLICT (id) DO NOTHING
            """
        ),
        {"id": CUSTOMER_MANUFACTURER_ID, "name": CUSTOMER_MANUFACTURER_NAME},
    )
    bind.execute(
        sa.text(
            """
            INSERT INTO dekorlar
                (id, manufacturer_id, tur, kod, nomi, image_file_id, tolali, holat, search_key)
            VALUES
                (:id, :manufacturer_id, CAST('boshqa' AS dekor_type), NULL, :nomi,
                 NULL, false, CAST('active' AS material_status), :search_key)
            ON CONFLICT (id) DO NOTHING
            """
        ),
        {
            "id": CUSTOMER_DEKOR_ID,
            "manufacturer_id": CUSTOMER_MANUFACTURER_ID,
            "nomi": CUSTOMER_DEKOR_NAME,
            # No `kod`, so the fold sees the manufacturer and the name only.
            "search_key": fold(f"{CUSTOMER_MANUFACTURER_NAME} {CUSTOMER_DEKOR_NAME}"),
        },
    )


def downgrade() -> None:
    bind = op.get_bind()
    # The non-partial index cannot be restored while customer rows exist — they
    # are exactly the rows the predicate was added to allow. Fail loudly rather
    # than dropping somebody's orders on the floor.
    remaining = bind.execute(
        sa.text("SELECT count(*) FROM branch_materials WHERE customer_supplied")
    ).scalar_one()
    if remaining:
        raise RuntimeError(
            f"{remaining} customer-supplied branch materials exist; "
            "delete them before downgrading or the unique index cannot be restored"
        )

    op.drop_index(_INDEX, table_name="branch_materials")
    op.create_index(
        _INDEX,
        "branch_materials",
        [
            "branch_id",
            "dekor_id",
            "qalinlik_mm",
            sa.text("coalesce(uzunlik_mm, 0)"),
            sa.text("coalesce(eni_mm, 0)"),
            sa.text("coalesce(kromka_eni_mm, 0)"),
        ],
        unique=True,
    )

    op.drop_index("ix_branch_materials_source_draft", table_name="branch_materials")
    op.drop_constraint("fk_branch_materials_stock_material", "branch_materials", type_="foreignkey")
    op.drop_constraint("fk_branch_materials_source_draft", "branch_materials", type_="foreignkey")
    op.drop_column("branch_materials", "stock_material_id")
    op.drop_column("branch_materials", "source_draft_id")
    op.drop_column("branch_materials", "tolali")
    op.drop_column("branch_materials", "nomi")
    op.drop_column("branch_materials", "customer_supplied")

    bind.execute(sa.text("DELETE FROM dekorlar WHERE id = :id"), {"id": CUSTOMER_DEKOR_ID})
    bind.execute(
        sa.text("DELETE FROM manufacturers WHERE id = :id"),
        {"id": CUSTOMER_MANUFACTURER_ID},
    )
