"""Supplier invoices gain a ledger status, a void reversal movement, and a doc number.

Hand-written, not autogenerated: two of the three changes are invisible to
autogenerate.

1. `stock_transaction_type` gains `stock_in_void` — an `ALTER TYPE ... ADD VALUE`
   autogenerate never emits. It runs in its own autocommit block because the
   CHECK constraint below *uses* the new label, and Postgres refuses to use an
   enum value added in the same transaction.
2. `ck_stock_transactions_invoice_stock_in_only` is relaxed so a reversal row
   keeps its `invoice_id` — the invoice has to read as a whole. The price CHECK
   is untouched: reversal rows carry no money.
3. `supplier_invoices` gains the finance ledger trio (`status` / `voided_reason`
   / `voided_by_user_id` / `voided_at`). Existing rows
   backfill to `recorded` via the server default, which is then dropped — the
   ORM supplies the value on every insert, exactly as `expenses` does.

Revision ID: e7a2c4d19b60
Revises: d4b18e6c07a9
Create Date: 2026-08-20
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7a2c4d19b60"
down_revision: str | None = "d4b18e6c07a9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_INVOICE_LINK_CHECK = "ck_stock_transactions_invoice_stock_in_only"


def upgrade() -> None:
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE stock_transaction_type ADD VALUE IF NOT EXISTS 'stock_in_void'")

    op.drop_constraint(_INVOICE_LINK_CHECK, "stock_transactions", type_="check")
    op.create_check_constraint(
        _INVOICE_LINK_CHECK,
        "stock_transactions",
        "invoice_id IS NULL OR type IN ('stock_in', 'stock_in_void')",
    )

    op.add_column(
        "supplier_invoices",
        sa.Column(
            "status",
            postgresql.ENUM("recorded", "voided", name="ledger_status", create_type=False),
            nullable=False,
            server_default="recorded",
        ),
    )
    op.alter_column("supplier_invoices", "status", server_default=None)
    op.add_column("supplier_invoices", sa.Column("voided_reason", sa.String(), nullable=True))
    op.add_column("supplier_invoices", sa.Column("voided_by_user_id", sa.Uuid(), nullable=True))
    op.add_column(
        "supplier_invoices",
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_foreign_key(
        "fk_supplier_invoices_voided_by_user_id_workshop_users",
        "supplier_invoices",
        "workshop_users",
        ["voided_by_user_id"],
        ["id"],
    )


def downgrade() -> None:
    # A voided invoice's reversal rows cannot survive the narrowed CHECK, and
    # dropping them would silently re-inflate stock. Fail loudly instead.
    remaining = (
        op.get_bind()
        .execute(sa.text("SELECT count(*) FROM stock_transactions WHERE type = 'stock_in_void'"))
        .scalar_one()
    )
    if remaining:
        raise RuntimeError(
            f"{remaining} stock_in_void movements exist; the invoice-link CHECK cannot be "
            "narrowed back to stock_in without dropping real stock history"
        )

    op.drop_constraint(
        "fk_supplier_invoices_voided_by_user_id_workshop_users",
        "supplier_invoices",
        type_="foreignkey",
    )
    op.drop_column("supplier_invoices", "voided_at")
    op.drop_column("supplier_invoices", "voided_by_user_id")
    op.drop_column("supplier_invoices", "voided_reason")
    op.drop_column("supplier_invoices", "status")

    op.drop_constraint(_INVOICE_LINK_CHECK, "stock_transactions", type_="check")
    op.create_check_constraint(
        _INVOICE_LINK_CHECK,
        "stock_transactions",
        "invoice_id IS NULL OR type = 'stock_in'",
    )
    # The enum label stays: Postgres cannot drop one, and recreating the type
    # would need every dependent column rewritten. It is inert without the CHECK.
