"""initial schema

Revision ID: f4c92c037584
Revises:
Create Date: 2026-05-20 20:38:45.879969
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4c92c037584"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_log",
        sa.Column(
            "actor_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                "SYSTEM",
                name="actortype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("summary", sa.String(length=400), nullable=True),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("trace_id", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_action_log_created_at"), "action_log", ["created_at"], unique=False)
    op.create_index(
        "ix_action_log_entity", "action_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_action_log_workshop", "action_log", ["workshop_id", "created_at"], unique=False
    )
    op.create_table(
        "client",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("first_name", sa.String(length=120), nullable=False),
        sa.Column("last_name", sa.String(length=120), nullable=True),
        sa.Column("photo_url", sa.String(length=512), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", name="userstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_client_telegram_id"), "client", ["telegram_id"], unique=True)
    op.create_table(
        "error_group",
        sa.Column("code", sa.String(length=120), nullable=False),
        sa.Column("module", sa.String(length=60), nullable=True),
        sa.Column("message_preview", sa.String(length=400), nullable=True),
        sa.Column("count_total", sa.Integer(), nullable=False),
        sa.Column("last_occurred_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum("OPEN", "RESOLVED", name="errorgroupstatus", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_error_group_code"), "error_group", ["code"], unique=True)
    op.create_table(
        "file",
        sa.Column("storage_key", sa.String(length=512), nullable=False),
        sa.Column("original_name", sa.String(length=300), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column(
            "storage_status",
            sa.Enum(
                "PENDING",
                "STORED",
                "DELETED",
                name="filestoragestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=True),
        sa.Column(
            "uploaded_by_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                name="principaltype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("uploaded_by_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_storage_key"), "file", ["storage_key"], unique=True)
    op.create_table(
        "job_run",
        sa.Column("job_name", sa.String(length=64), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "result",
            sa.Enum("OK", "FAILED", "RUNNING", name="jobrunresult", native_enum=False, length=12),
            nullable=False,
        ),
        sa.Column("log", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_run_job_name"), "job_run", ["job_name"], unique=False)
    op.create_table(
        "material",
        sa.Column(
            "kind",
            sa.Enum("SHEET", "EDGE", name="materialkind", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum(
                "DSP",
                "MDF",
                "PLYWOOD",
                "NATURAL_WOOD",
                "OTHER",
                name="materialtype",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("thickness_mm", sa.Numeric(precision=6, scale=2), nullable=False),
        sa.Column("color", sa.String(length=80), nullable=False),
        sa.Column("decor_code", sa.String(length=80), nullable=True),
        sa.Column("sheet_length_mm", sa.Integer(), nullable=True),
        sa.Column("sheet_width_mm", sa.Integer(), nullable=True),
        sa.Column("grain_direction", sa.Boolean(), nullable=True),
        sa.Column("image_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="catalogstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification",
        sa.Column(
            "recipient_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                name="principaltype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("event_code", sa.String(length=60), nullable=False),
        sa.Column("entity_type", sa.String(length=40), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_created_at"), "notification", ["created_at"], unique=False
    )
    op.create_index(
        "ix_notification_recipient",
        "notification",
        ["recipient_type", "recipient_id", "read_at"],
        unique=False,
    )
    op.create_table(
        "platform_user",
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", name="userstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_platform_user_login"), "platform_user", ["login"], unique=True)
    op.create_table(
        "session",
        sa.Column(
            "principal_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                name="principaltype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("principal_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_hash", sa.String(length=64), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("refresh_token_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_info", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_used_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_session_access_token_hash"), "session", ["access_token_hash"], unique=True
    )
    op.create_index(
        "ix_session_principal", "session", ["principal_type", "principal_id"], unique=False
    )
    op.create_index(
        op.f("ix_session_refresh_token_hash"), "session", ["refresh_token_hash"], unique=True
    )
    op.create_table(
        "status_change_log",
        sa.Column("entity_type", sa.String(length=40), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column("from_status", sa.String(length=24), nullable=True),
        sa.Column("to_status", sa.String(length=24), nullable=False),
        sa.Column(
            "actor_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                "SYSTEM",
                name="actortype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("action_log_id", sa.Uuid(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_change_entity", "status_change_log", ["entity_type", "entity_id"], unique=False
    )
    op.create_index(
        "ix_status_change_workshop",
        "status_change_log",
        ["workshop_id", "changed_at"],
        unique=False,
    )
    op.create_table(
        "workshop",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("logo_file_id", sa.Uuid(), nullable=True),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=400), nullable=True),
        sa.Column("owner_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", name="workshopstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column(
            "currency", sa.Enum("UZS", name="currency", native_enum=False, length=8), nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branch",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("address", sa.String(length=400), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("working_hours", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "TEMPORARILY_CLOSED",
                "INACTIVE",
                name="branchstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("closed_reason", sa.String(length=300), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_branch_workshop", "branch", ["workshop_id"], unique=False)
    op.create_table(
        "cutting_draft",
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("parts_snapshot", sa.JSON(), nullable=False),
        sa.Column("chosen_result_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cutting_draft_client_id"), "cutting_draft", ["client_id"], unique=False
    )
    op.create_table(
        "error_event",
        sa.Column("error_group_id", sa.Uuid(), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("stack", sa.Text(), nullable=True),
        sa.Column("context", sa.JSON(), nullable=True),
        sa.Column("trace_id", sa.String(length=40), nullable=True),
        sa.Column("workshop_id", sa.Uuid(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["error_group_id"],
            ["error_group.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_error_event_error_group_id"), "error_event", ["error_group_id"], unique=False
    )
    op.create_index(
        op.f("ix_error_event_occurred_at"), "error_event", ["occurred_at"], unique=False
    )
    op.create_table(
        "supplier",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="supplierstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("created_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_supplier_workshop_id"), "supplier", ["workshop_id"], unique=False)
    op.create_table(
        "branch_material",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="catalogstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "material_id", name="uq_branch_material"),
    )
    op.create_index(
        op.f("ix_branch_material_branch_id"), "branch_material", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_branch_material_material_id"), "branch_material", ["material_id"], unique=False
    )
    op.create_table(
        "branch_pricing",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column(
            "cutting_model",
            sa.Enum("PER_SHEET", "PER_CUT", name="cuttingmodel", native_enum=False, length=16),
            nullable=True,
        ),
        sa.Column("cutting_rate_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("edge_banding_rates", sa.JSON(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("updated_by_user_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.PrimaryKeyConstraint("branch_id"),
    )
    op.create_table(
        "cutting_result",
        sa.Column("draft_id", sa.Uuid(), nullable=True),
        sa.Column("algorithm_name", sa.String(length=64), nullable=False),
        sa.Column("algorithm_version", sa.String(length=16), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CANDIDATE",
                "CONFIRMED",
                "INVALIDATED",
                name="cuttingresultstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("kerf_mm", sa.Integer(), nullable=False),
        sa.Column("edge_trim_mm", sa.Integer(), nullable=False),
        sa.Column("sheets_used_by_material", sa.JSON(), nullable=False),
        sa.Column("waste_percentage", sa.Numeric(precision=6, scale=4), nullable=False),
        sa.Column("total_cut_length_mm", sa.Integer(), nullable=False),
        sa.Column("total_edge_length_mm", sa.Integer(), nullable=False),
        sa.Column("edge_length_by_thickness", sa.JSON(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("invalidated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"],
            ["cutting_draft.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cutting_result_draft_id"), "cutting_result", ["draft_id"], unique=False
    )
    op.create_index(
        op.f("ix_cutting_result_order_id"), "cutting_result", ["order_id"], unique=False
    )
    op.create_table(
        "expense",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "category",
            sa.Enum(
                "RENT",
                "UTILITIES",
                "RAW_MATERIALS",
                "SUPPLIES",
                "TRANSPORT",
                "EQUIPMENT",
                "MARKETING",
                "TAXES_AND_FEES",
                "SALARY",
                "OTHER",
                name="expensecategory",
                native_enum=False,
                length=24,
            ),
            nullable=False,
        ),
        sa.Column("amount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("incurred_on", sa.Date(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("vendor", sa.String(length=200), nullable=True),
        sa.Column("receipt_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RECORDED", "VOIDED", name="ledgerstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("voided_reason", sa.String(length=500), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_expense_branch_id"), "expense", ["branch_id"], unique=False)
    op.create_index(op.f("ix_expense_workshop_id"), "expense", ["workshop_id"], unique=False)
    op.create_table(
        "order",
        sa.Column("order_number", sa.String(length=24), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("cutting_result_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "CUTTING",
                "EDGE_BANDING",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("note_client", sa.String(length=1000), nullable=True),
        sa.Column("note_workshop", sa.String(length=1000), nullable=True),
        sa.Column("contact_name", sa.String(length=120), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("subtotal_cutting_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_materials_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("subtotal_edge_banding_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("discount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("discount_reason", sa.String(length=300), nullable=True),
        sa.Column("discount_applied_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("total_tiyin", sa.BigInteger(), nullable=False),
        sa.Column(
            "currency", sa.Enum("UZS", name="currency", native_enum=False, length=8), nullable=False
        ),
        sa.Column("assigned_cutter_user_id", sa.Uuid(), nullable=True),
        sa.Column("assigned_edger_user_id", sa.Uuid(), nullable=True),
        sa.Column("cutter_user_id", sa.Uuid(), nullable=True),
        sa.Column("cut_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sheets_used_snapshot", sa.Integer(), nullable=True),
        sa.Column("cut_count_snapshot", sa.Integer(), nullable=True),
        sa.Column("edger_user_id", sa.Uuid(), nullable=True),
        sa.Column("edge_completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("edge_length_snapshot", sa.JSON(), nullable=True),
        sa.Column("picked_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["client.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_branch_id"), "order", ["branch_id"], unique=False)
    op.create_index(op.f("ix_order_client_id"), "order", ["client_id"], unique=False)
    op.create_index(op.f("ix_order_order_number"), "order", ["order_number"], unique=True)
    op.create_index(op.f("ix_order_status"), "order", ["status"], unique=False)
    op.create_index(op.f("ix_order_workshop_id"), "order", ["workshop_id"], unique=False)
    op.create_table(
        "stock_item",
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Integer(), nullable=False),
        sa.Column("min_stock", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["material.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("branch_id", "material_id", name="uq_stock_item"),
    )
    op.create_index(op.f("ix_stock_item_branch_id"), "stock_item", ["branch_id"], unique=False)
    op.create_index(op.f("ix_stock_item_material_id"), "stock_item", ["material_id"], unique=False)
    op.create_table(
        "workshop_user",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("login", sa.String(length=64), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=120), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("is_owner", sa.Boolean(), nullable=False),
        sa.Column("home_branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "BLOCKED", name="userstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("force_password_change", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["home_branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("workshop_id", "login", name="uq_workshop_user_login"),
    )
    op.create_index("ix_workshop_user_workshop", "workshop_user", ["workshop_id"], unique=False)
    op.create_table(
        "cutting_sheet",
        sa.Column("cutting_result_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column("sheet_index", sa.Integer(), nullable=False),
        sa.Column("waste_area_mm2", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cutting_result_id"],
            ["cutting_result.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cutting_sheet_cutting_result_id"),
        "cutting_sheet",
        ["cutting_result_id"],
        unique=False,
    )
    op.create_table(
        "income",
        sa.Column("workshop_id", sa.Uuid(), nullable=False),
        sa.Column("branch_id", sa.Uuid(), nullable=True),
        sa.Column(
            "type",
            sa.Enum("ORDER_PAYMENT", "OTHER", name="incometype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("amount_tiyin", sa.BigInteger(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "CASH", "BANK_TRANSFER", "OTHER", name="paymentmethod", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("received_on", sa.Date(), nullable=False),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("receipt_file_id", sa.Uuid(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("RECORDED", "VOIDED", name="ledgerstatus", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("voided_reason", sa.String(length=500), nullable=True),
        sa.Column("recorded_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("voided_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("voided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_id"],
            ["workshop.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_income_branch_id"), "income", ["branch_id"], unique=False)
    op.create_index(op.f("ix_income_order_id"), "income", ["order_id"], unique=False)
    op.create_index(op.f("ix_income_workshop_id"), "income", ["workshop_id"], unique=False)
    op.create_table(
        "order_cancellation",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "cancelled_by_type",
            sa.Enum(
                "CLIENT", "WORKSHOP_USER", name="cancelledbytype", native_enum=False, length=16
            ),
            nullable=False,
        ),
        sa.Column("cancelled_by_user_id", sa.Uuid(), nullable=True),
        sa.Column("cancelled_by_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=False),
        sa.Column(
            "cancelled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_id"),
    )
    op.create_table(
        "order_item",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("material_id", sa.Uuid(), nullable=False),
        sa.Column(
            "material_source",
            sa.Enum("SHOP", "OWN", name="materialsource", native_enum=False, length=8),
            nullable=False,
        ),
        sa.Column("material_snapshot", sa.JSON(), nullable=False),
        sa.Column("part_ref", sa.String(length=64), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("edge_top_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("edge_bottom_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("edge_left_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("edge_right_mm", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("unit_cutting_price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("unit_material_price_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("edge_cost_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("line_total_tiyin", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_item_order_id"), "order_item", ["order_id"], unique=False)
    op.create_table(
        "order_status_event",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "CUTTING",
                "EDGE_BANDING",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "NEW",
                "CONFIRMED",
                "CUTTING",
                "EDGE_BANDING",
                "READY",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column(
            "actor_type",
            sa.Enum(
                "PLATFORM_USER",
                "WORKSHOP_USER",
                "CLIENT",
                "SYSTEM",
                name="actortype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("actor_client_id", sa.Uuid(), nullable=True),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("event_metadata", sa.JSON(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_status_event_order_id"), "order_status_event", ["order_id"], unique=False
    )
    op.create_table(
        "permission_grant",
        sa.Column("workshop_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "permission",
            sa.Enum(
                "VIEW_DASHBOARD",
                "MANAGE_ORDERS",
                "PROCESS_PRODUCTION",
                "MANAGE_CATALOG",
                "MANAGE_INVENTORY",
                "MANAGE_FINANCE",
                "VIEW_FINANCE_REPORTS",
                name="permission",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("branch_id", sa.Uuid(), nullable=False),
        sa.Column("granted_by_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branch.id"],
        ),
        sa.ForeignKeyConstraint(
            ["granted_by_user_id"],
            ["workshop_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["workshop_user_id"],
            ["workshop_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "workshop_user_id", "permission", "branch_id", name="uq_permission_grant"
        ),
    )
    op.create_index(
        op.f("ix_permission_grant_branch_id"), "permission_grant", ["branch_id"], unique=False
    )
    op.create_index(
        op.f("ix_permission_grant_workshop_user_id"),
        "permission_grant",
        ["workshop_user_id"],
        unique=False,
    )
    op.create_table(
        "stock_transaction",
        sa.Column("stock_item_id", sa.Uuid(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "STOCK_IN",
                "CONSUME",
                "RESTORE",
                "ADJUST",
                name="stocktransactiontype",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("balance_after", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=True),
        sa.Column("supplier_id", sa.Uuid(), nullable=True),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("note", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["stock_item_id"],
            ["stock_item.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_stock_transaction_order_id"), "stock_transaction", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_transaction_stock_item_id"),
        "stock_transaction",
        ["stock_item_id"],
        unique=False,
    )
    op.create_table(
        "cutting_placement",
        sa.Column("cutting_sheet_id", sa.Uuid(), nullable=False),
        sa.Column("part_ref", sa.String(length=64), nullable=False),
        sa.Column("part_quantity_index", sa.Integer(), nullable=False),
        sa.Column("x_mm", sa.Integer(), nullable=False),
        sa.Column("y_mm", sa.Integer(), nullable=False),
        sa.Column("length_mm", sa.Integer(), nullable=False),
        sa.Column("width_mm", sa.Integer(), nullable=False),
        sa.Column("rotated", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cutting_sheet_id"],
            ["cutting_sheet.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_cutting_placement_cutting_sheet_id"),
        "cutting_placement",
        ["cutting_sheet_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cutting_placement_cutting_sheet_id"), table_name="cutting_placement")
    op.drop_table("cutting_placement")
    op.drop_index(op.f("ix_stock_transaction_stock_item_id"), table_name="stock_transaction")
    op.drop_index(op.f("ix_stock_transaction_order_id"), table_name="stock_transaction")
    op.drop_table("stock_transaction")
    op.drop_index(op.f("ix_permission_grant_workshop_user_id"), table_name="permission_grant")
    op.drop_index(op.f("ix_permission_grant_branch_id"), table_name="permission_grant")
    op.drop_table("permission_grant")
    op.drop_index(op.f("ix_order_status_event_order_id"), table_name="order_status_event")
    op.drop_table("order_status_event")
    op.drop_index(op.f("ix_order_item_order_id"), table_name="order_item")
    op.drop_table("order_item")
    op.drop_table("order_cancellation")
    op.drop_index(op.f("ix_income_workshop_id"), table_name="income")
    op.drop_index(op.f("ix_income_order_id"), table_name="income")
    op.drop_index(op.f("ix_income_branch_id"), table_name="income")
    op.drop_table("income")
    op.drop_index(op.f("ix_cutting_sheet_cutting_result_id"), table_name="cutting_sheet")
    op.drop_table("cutting_sheet")
    op.drop_index("ix_workshop_user_workshop", table_name="workshop_user")
    op.drop_table("workshop_user")
    op.drop_index(op.f("ix_stock_item_material_id"), table_name="stock_item")
    op.drop_index(op.f("ix_stock_item_branch_id"), table_name="stock_item")
    op.drop_table("stock_item")
    op.drop_index(op.f("ix_order_workshop_id"), table_name="order")
    op.drop_index(op.f("ix_order_status"), table_name="order")
    op.drop_index(op.f("ix_order_order_number"), table_name="order")
    op.drop_index(op.f("ix_order_client_id"), table_name="order")
    op.drop_index(op.f("ix_order_branch_id"), table_name="order")
    op.drop_table("order")
    op.drop_index(op.f("ix_expense_workshop_id"), table_name="expense")
    op.drop_index(op.f("ix_expense_branch_id"), table_name="expense")
    op.drop_table("expense")
    op.drop_index(op.f("ix_cutting_result_order_id"), table_name="cutting_result")
    op.drop_index(op.f("ix_cutting_result_draft_id"), table_name="cutting_result")
    op.drop_table("cutting_result")
    op.drop_table("branch_pricing")
    op.drop_index(op.f("ix_branch_material_material_id"), table_name="branch_material")
    op.drop_index(op.f("ix_branch_material_branch_id"), table_name="branch_material")
    op.drop_table("branch_material")
    op.drop_index(op.f("ix_supplier_workshop_id"), table_name="supplier")
    op.drop_table("supplier")
    op.drop_index(op.f("ix_error_event_occurred_at"), table_name="error_event")
    op.drop_index(op.f("ix_error_event_error_group_id"), table_name="error_event")
    op.drop_table("error_event")
    op.drop_index(op.f("ix_cutting_draft_client_id"), table_name="cutting_draft")
    op.drop_table("cutting_draft")
    op.drop_index("ix_branch_workshop", table_name="branch")
    op.drop_table("branch")
    op.drop_table("workshop")
    op.drop_index("ix_status_change_workshop", table_name="status_change_log")
    op.drop_index("ix_status_change_entity", table_name="status_change_log")
    op.drop_table("status_change_log")
    op.drop_index(op.f("ix_session_refresh_token_hash"), table_name="session")
    op.drop_index("ix_session_principal", table_name="session")
    op.drop_index(op.f("ix_session_access_token_hash"), table_name="session")
    op.drop_table("session")
    op.drop_index(op.f("ix_platform_user_login"), table_name="platform_user")
    op.drop_table("platform_user")
    op.drop_index("ix_notification_recipient", table_name="notification")
    op.drop_index(op.f("ix_notification_created_at"), table_name="notification")
    op.drop_table("notification")
    op.drop_table("material")
    op.drop_index(op.f("ix_job_run_job_name"), table_name="job_run")
    op.drop_table("job_run")
    op.drop_index(op.f("ix_file_storage_key"), table_name="file")
    op.drop_table("file")
    op.drop_index(op.f("ix_error_group_code"), table_name="error_group")
    op.drop_table("error_group")
    op.drop_index(op.f("ix_client_telegram_id"), table_name="client")
    op.drop_table("client")
    op.drop_index("ix_action_log_workshop", table_name="action_log")
    op.drop_index("ix_action_log_entity", table_name="action_log")
    op.drop_index(op.f("ix_action_log_created_at"), table_name="action_log")
    op.drop_table("action_log")
    # ### end Alembic commands ###
